# -*- coding: utf-8 -*-
"""Copy of main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_lfV6lTezYa6vG_U_rVBnfl8zK9zmpA

# Phase 0: EDA
"""

"""### Basic Overview"""

import pandas as pd

df = pd.read_csv("data/beijing.csv")

# Basic info
print("Shape: ", df.shape)
print("Dtypes:\n",df.dtypes)
print(df.head())

# Quick stats
df.describe()

df.isna().sum()

"""### Missing Values Heatmap"""

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
sns.heatmap(df.isnull(), cbar=False, cmap="viridis")
plt.title("Missing Values Heatmap")
plt.show()

"""### Histograms of Key Variables"""

pollutants = ['pm2_5', 'pm10', 'co', 'no2', 'so2', 'o3', 'no', 'nh3']
weather = ['temperature', 'dewpt']

df[pollutants + weather].hist(figsize=(14, 10), bins=30)
plt.suptitle("Distributions of Pollutants & Weather Features")
plt.tight_layout()
plt.show()

"""### Time Series Plots"""

# Parse datetime
df['datetime'] = pd.to_datetime(df[['year', 'month', 'day', 'hour']])
df.set_index('datetime', inplace=True)

for pollutant in pollutants:
# Plot pollutants over time
    df[pollutant].plot(figsize=(15, 6), alpha=0.7)
    plt.title(f"Time Series of {pollutant}")
    plt.ylabel("Concentration")
    plt.show()

"""### Correlation Heatmap"""

import matplotlib.pyplot as plt

# Plotting the bar chart
hourly_avg.plot(kind='bar', figsize=(10, 4))

# Enlarge the title, labels, and legend
plt.title("Average Pollution by Hour of Day", fontsize=25)  # Enlarge title
plt.ylabel("Concentration", fontsize=15)  # Enlarge y-axis label
plt.xlabel("Hour", fontsize=15)  # Enlarge x-axis label
plt.xticks(rotation=0, fontsize=12)  # Enlarge x-tick labels
plt.yticks(fontsize=12)  # Enlarge y-tick labels
plt.legend(fontsize=12)  # Enlarge legend text

# Show the plot
plt.show()

plt.figure(figsize=(12, 10))
corr = df[pollutants + weather].corr()

# rename columns and index only for plotting
corr = corr.rename(columns={"temperature": "tmp"}, index={"temperature": "tmp"})

sns.heatmap(
    corr,
    annot=True,
    cmap="coolwarm",
    center=0,
    annot_kws={"size": 16}
)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.title("Correlation Between Pollutants and Weather Features", fontsize=20)
plt.show()
